#!/usr/bin/env python3
"""
calculate_avg_acr_cost.py
Recursively discovers all `cost.json` files generated by AutoCodeRover,
identifies whether a patch was produced, extracts token counts/costs,
and calculates statistical averages (All Attempted vs. Patch-Producing Only).

Uses Python standard library only (no external dependencies).

Usage:
    python /root/AgentBug-Smith/tools/calculate_avg_acr_cost.py \
        --results-dir /root/AgentBug-Smith/results/patches/auto-code-rover-patches
"""

import argparse
import json
import statistics
from pathlib import Path

# ============================================================
# Fixed Rate Card for GPT-4.1-mini ($ / 1M tokens)
# $0.40/1M uncached input, $0.10/1M cached input, $1.60/1M output
# ============================================================
RATES = {
    "uncached_in": 0.40 / 1_000_000,
    "cached_in": 0.10 / 1_000_000,
    "out": 1.60 / 1_000_000,
}


def check_has_patch(result_dir: Path) -> bool:
    """Checks whether the result directory contains a non-empty patch/diff file."""
    patch_candidates = [
        result_dir / "generated_patch.diff",
        result_dir / "generated_patch.patch",
    ]
    patch_candidates.extend(result_dir.glob("*.diff"))
    patch_candidates.extend(result_dir.glob("*.patch"))
    patch_candidates.extend((result_dir / "acr_output").rglob("*.diff"))
    patch_candidates.extend((result_dir / "acr_output").rglob("*.patch"))

    for p in patch_candidates:
        if p.is_file() and p.stat().st_size > 0:
            content = p.read_text(errors="ignore").strip()
            if content:
                return True
    return False


def parse_acr_instance(cost_file: Path) -> dict | None:
    """Parses a single cost.json file and associates it with the task directory."""
    try:
        data = json.loads(cost_file.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"[-] Failed to read {cost_file}: {e}")
        return None

    # Locate the root result_<instance_id> directory
    result_folder = None
    instance_id = "unknown"
    for parent in cost_file.parents:
        if parent.name.startswith("result_"):
            result_folder = parent
            instance_id = parent.name.replace("result_", "")
            break

    if result_folder is None:
        result_folder = cost_file.parent
        instance_id = cost_file.parent.name

    has_patch = check_has_patch(result_folder)

    input_tokens = (
        data.get("input_tokens")
        or data.get("prompt_tokens")
        or data.get("total_input_tokens")
        or 0
    )
    cached_tokens = (
        data.get("cached_tokens")
        or data.get("cached_prompt_tokens")
        or 0
    )
    output_tokens = (
        data.get("output_tokens")
        or data.get("completion_tokens")
        or data.get("total_output_tokens")
        or 0
    )
    recorded_cost = (
        data.get("total_cost")
        or data.get("cost")
        or data.get("cost_usd")
        or 0.0
    )

    uncached_input = max(0, input_tokens - cached_tokens)
    recalculated_cost = (
        (uncached_input * RATES["uncached_in"])
        + (cached_tokens * RATES["cached_in"])
        + (output_tokens * RATES["out"])
    )

    cost_to_use = recorded_cost if recorded_cost > 0 else recalculated_cost

    return {
        "instance_id": instance_id,
        "has_patch": has_patch,
        "input_tokens": input_tokens,
        "cached_tokens": cached_tokens,
        "uncached_tokens": uncached_input,
        "output_tokens": output_tokens,
        "total_tokens": input_tokens + output_tokens,
        "recorded_cost_usd": round(recorded_cost, 6),
        "recalculated_cost_usd": round(recalculated_cost, 6),
        "cost_usd": round(cost_to_use, 6),
        "cost_file": str(cost_file),
    }


def compute_metrics(records: list[dict]) -> dict:
    """Computes mean and std stats for a list of task records."""
    if not records:
        return {
            "count": 0,
            "total_cost": 0.0,
            "avg_cost": 0.0,
            "std_cost": 0.0,
            "avg_tokens": 0.0,
            "avg_input_tokens": 0.0,
            "avg_cached_tokens": 0.0,
            "avg_output_tokens": 0.0,
        }

    n = len(records)
    costs = [r["cost_usd"] for r in records]
    inputs = [r["input_tokens"] for r in records]
    cached = [r["cached_tokens"] for r in records]
    outputs = [r["output_tokens"] for r in records]
    totals = [r["total_tokens"] for r in records]

    return {
        "count": n,
        "total_cost": sum(costs),
        "avg_cost": statistics.mean(costs),
        "std_cost": statistics.stdev(costs) if n > 1 else 0.0,
        "avg_tokens": statistics.mean(totals),
        "avg_input_tokens": statistics.mean(inputs),
        "avg_cached_tokens": statistics.mean(cached),
        "avg_output_tokens": statistics.mean(outputs),
    }


def main():
    parser = argparse.ArgumentParser(
        description="Compute AutoCodeRover cost statistics for GPT-4.1-mini."
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        required=True,
        help="Root directory containing AutoCodeRover patches and runs.",
    )
    args = parser.parse_args()

    # Discover cost.json files recursively
    cost_files = sorted(list(args.results_dir.rglob("cost.json")))
    if not cost_files:
        print(f"[-] No cost.json files found under: {args.results_dir}")
        return

    records = []
    seen_instances = set()
    for cf in cost_files:
        parsed = parse_acr_instance(cf)
        if parsed:
            # Prevent duplicate count if run artifact contains multiple sub-dumps
            if parsed["instance_id"] in seen_instances:
                continue
            seen_instances.add(parsed["instance_id"])
            records.append(parsed)

    if not records:
        print("[-] Could not extract records from cost.json files.")
        return

    # Sort by instance ID
    records.sort(key=lambda x: x["instance_id"])

    # Table breakdown
    print(f"\n{'Instance ID':<38} | {'Patch?':<6} | {'Input Tok':<10} | {'Cached':<8} | {'Output':<8} | {'Cost (USD)':<10}")
    print("-" * 92)

    for r in records:
        patch_flag = "YES" if r["has_patch"] else "NO"
        print(
            f"{r['instance_id'][:38]:<38} | "
            f"{patch_flag:<6} | "
            f"{r['input_tokens']:<10} | "
            f"{r['cached_tokens']:<8} | "
            f"{r['output_tokens']:<8} | "
            f"${r['cost_usd']:<9.4f}"
        )

    # Compute stats for both groups
    all_stats = compute_metrics(records)
    patch_only_records = [r for r in records if r["has_patch"]]
    patch_stats = compute_metrics(patch_only_records)
    no_patch_records = [r for r in records if not r["has_patch"]]

    print("=" * 92)
    print(f"1. Overall (All Attempted Tasks) [Standard Benchmark Metric]:")
    print(f"  • Total Issues Attempted          : {all_stats['count']}")
    print(f"  • Patches Produced                : {patch_stats['count']} (Empty/Failed: {len(no_patch_records)})")
    print(f"  • Total Cost                      : ${all_stats['total_cost']:.4f}")
    print(f"  • Average Cost per Task           : ${all_stats['avg_cost']:.4f} (± ${all_stats['std_cost']:.4f})")
    print(f"  • Average Total Tokens / Task     : {all_stats['avg_tokens']:,.1f}")
    print(f"  • Average Input / Cached / Output : {all_stats['avg_input_tokens']:,.1f} / {all_stats['avg_cached_tokens']:,.1f} / {all_stats['avg_output_tokens']:,.1f}")

    print("-" * 92)
    print(f"2. Conditional (Patch-Producing Only):")
    print(f"  • Average Cost per Produced Patch : ${patch_stats['avg_cost']:.4f} (± ${patch_stats['std_cost']:.4f})")
    print(f"  • Average Total Tokens / Patch    : {patch_stats['avg_tokens']:,.1f}")
    print("=" * 92)

    # Save summary report JSON
    summary_path = args.results_dir / "acr_cost_summary.json"
    summary_data = {
        "model": "gpt-4.1-mini",
        "pricing_per_1m": {"uncached_input": 0.40, "cached_input": 0.10, "output": 1.60},
        "all_attempted": all_stats,
        "patch_producing_only": patch_stats,
        "details": records,
    }
    summary_path.write_text(json.dumps(summary_data, indent=2), encoding="utf-8")
    print(f"[✓] Complete summary JSON written to: {summary_path}\n")


if __name__ == "__main__":
    main()